# Remove result files and directories generated by run_rand and run scripts
foreach file [list \
    ../result_files/res_file_img_* \
    ../uvm_project \
    ../uvm_rand_project \
    ../regression_log.txt \
    ../regression_log_rand.txt \
] {
    foreach f [glob -nocomplain $file] {
        if {[file exists $f]} {
            file delete -force $f
        }
    }
}

puts "Cleanup complete."